// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type loopbackgwPortKey struct {
	_     structs.HostLayout
	Proto uint8
	Pad0  uint8
	Addr  [16]uint8
	Port  uint16
	Pad1  [2]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	loopbackgwMapGuestPorts    = "guest_ports"
	loopbackgwMapMacPorts      = "mac_ports"
	loopbackgwProgConnect4     = "connect4"
	loopbackgwProgConnect6     = "connect6"
	loopbackgwProgGetpeername4 = "getpeername4"
	loopbackgwProgGetpeername6 = "getpeername6"
	loopbackgwProgRecvmsg4     = "recvmsg4"
	loopbackgwProgRecvmsg6     = "recvmsg6"
	loopbackgwProgSendmsg4     = "sendmsg4"
	loopbackgwProgSendmsg6     = "sendmsg6"
)

// loadLoopbackgw returns the embedded CollectionSpec for loopbackgw.
func loadLoopbackgw() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LoopbackgwBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load loopbackgw: %w", err)
	}

	return spec, err
}

// loadLoopbackgwObjects loads loopbackgw and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*loopbackgwObjects
//	*loopbackgwPrograms
//	*loopbackgwMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLoopbackgwObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadLoopbackgw()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// loopbackgwSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type loopbackgwSpecs struct {
	loopbackgwProgramSpecs
	loopbackgwMapSpecs
	loopbackgwVariableSpecs
}

// loopbackgwProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type loopbackgwProgramSpecs struct {
	Connect4     *ebpf.ProgramSpec `ebpf:"connect4"`
	Connect6     *ebpf.ProgramSpec `ebpf:"connect6"`
	Getpeername4 *ebpf.ProgramSpec `ebpf:"getpeername4"`
	Getpeername6 *ebpf.ProgramSpec `ebpf:"getpeername6"`
	Recvmsg4     *ebpf.ProgramSpec `ebpf:"recvmsg4"`
	Recvmsg6     *ebpf.ProgramSpec `ebpf:"recvmsg6"`
	Sendmsg4     *ebpf.ProgramSpec `ebpf:"sendmsg4"`
	Sendmsg6     *ebpf.ProgramSpec `ebpf:"sendmsg6"`
}

// loopbackgwMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type loopbackgwMapSpecs struct {
	GuestPorts *ebpf.MapSpec `ebpf:"guest_ports"`
	MacPorts   *ebpf.MapSpec `ebpf:"mac_ports"`
}

// loopbackgwVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type loopbackgwVariableSpecs struct {
}

// loopbackgwObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLoopbackgwObjects or ebpf.CollectionSpec.LoadAndAssign.
type loopbackgwObjects struct {
	loopbackgwPrograms
	loopbackgwMaps
	loopbackgwVariables
}

func (o *loopbackgwObjects) Close() error {
	return _LoopbackgwClose(
		&o.loopbackgwPrograms,
		&o.loopbackgwMaps,
	)
}

// loopbackgwMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLoopbackgwObjects or ebpf.CollectionSpec.LoadAndAssign.
type loopbackgwMaps struct {
	GuestPorts *ebpf.Map `ebpf:"guest_ports"`
	MacPorts   *ebpf.Map `ebpf:"mac_ports"`
}

func (m *loopbackgwMaps) Close() error {
	return _LoopbackgwClose(
		m.GuestPorts,
		m.MacPorts,
	)
}

// loopbackgwVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLoopbackgwObjects or ebpf.CollectionSpec.LoadAndAssign.
type loopbackgwVariables struct {
}

// loopbackgwPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLoopbackgwObjects or ebpf.CollectionSpec.LoadAndAssign.
type loopbackgwPrograms struct {
	Connect4     *ebpf.Program `ebpf:"connect4"`
	Connect6     *ebpf.Program `ebpf:"connect6"`
	Getpeername4 *ebpf.Program `ebpf:"getpeername4"`
	Getpeername6 *ebpf.Program `ebpf:"getpeername6"`
	Recvmsg4     *ebpf.Program `ebpf:"recvmsg4"`
	Recvmsg6     *ebpf.Program `ebpf:"recvmsg6"`
	Sendmsg4     *ebpf.Program `ebpf:"sendmsg4"`
	Sendmsg6     *ebpf.Program `ebpf:"sendmsg6"`
}

func (p *loopbackgwPrograms) Close() error {
	return _LoopbackgwClose(
		p.Connect4,
		p.Connect6,
		p.Getpeername4,
		p.Getpeername6,
		p.Recvmsg4,
		p.Recvmsg6,
		p.Sendmsg4,
		p.Sendmsg6,
	)
}

func _LoopbackgwClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed loopbackgw_bpfel.o
var _LoopbackgwBytes []byte
