// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type trackerListenerEvent struct {
	_     structs.HostLayout
	Op    uint8
	Proto uint8
	Port  uint16
	Addr  [16]uint8
}

type trackerPortKey struct {
	_     structs.HostLayout
	Proto uint8
	Pad0  uint8
	Addr  [16]uint8
	Port  uint16
	Pad1  [2]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	trackerMapGuestPorts          = "guest_ports"
	trackerMapSkKeys              = "sk_keys"
	trackerMapTrackerEvents       = "tracker_events"
	trackerProgTcpListenStart     = "tcp_listen_start"
	trackerProgTcpListenStop      = "tcp_listen_stop"
	trackerProgUdp4Bind           = "udp4_bind"
	trackerProgUdp6Bind           = "udp6_bind"
	trackerProgUdpUnbind          = "udp_unbind"
	trackerVarHostNetnsInum       = "host_netns_inum"
	trackerVarUnusedListenerEvent = "unused_listener_event"
)

// loadTracker returns the embedded CollectionSpec for tracker.
func loadTracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TrackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tracker: %w", err)
	}

	return spec, err
}

// loadTrackerObjects loads tracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*trackerObjects
//	*trackerPrograms
//	*trackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTrackerObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// trackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trackerSpecs struct {
	trackerProgramSpecs
	trackerMapSpecs
	trackerVariableSpecs
}

// trackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trackerProgramSpecs struct {
	TcpListenStart *ebpf.ProgramSpec `ebpf:"tcp_listen_start"`
	TcpListenStop  *ebpf.ProgramSpec `ebpf:"tcp_listen_stop"`
	Udp4Bind       *ebpf.ProgramSpec `ebpf:"udp4_bind"`
	Udp6Bind       *ebpf.ProgramSpec `ebpf:"udp6_bind"`
	UdpUnbind      *ebpf.ProgramSpec `ebpf:"udp_unbind"`
}

// trackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trackerMapSpecs struct {
	GuestPorts    *ebpf.MapSpec `ebpf:"guest_ports"`
	SkKeys        *ebpf.MapSpec `ebpf:"sk_keys"`
	TrackerEvents *ebpf.MapSpec `ebpf:"tracker_events"`
}

// trackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trackerVariableSpecs struct {
	HostNetnsInum       *ebpf.VariableSpec `ebpf:"host_netns_inum"`
	UnusedListenerEvent *ebpf.VariableSpec `ebpf:"unused_listener_event"`
}

// trackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type trackerObjects struct {
	trackerPrograms
	trackerMaps
	trackerVariables
}

func (o *trackerObjects) Close() error {
	return _TrackerClose(
		&o.trackerPrograms,
		&o.trackerMaps,
	)
}

// trackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type trackerMaps struct {
	GuestPorts    *ebpf.Map `ebpf:"guest_ports"`
	SkKeys        *ebpf.Map `ebpf:"sk_keys"`
	TrackerEvents *ebpf.Map `ebpf:"tracker_events"`
}

func (m *trackerMaps) Close() error {
	return _TrackerClose(
		m.GuestPorts,
		m.SkKeys,
		m.TrackerEvents,
	)
}

// trackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type trackerVariables struct {
	HostNetnsInum       *ebpf.Variable `ebpf:"host_netns_inum"`
	UnusedListenerEvent *ebpf.Variable `ebpf:"unused_listener_event"`
}

// trackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type trackerPrograms struct {
	TcpListenStart *ebpf.Program `ebpf:"tcp_listen_start"`
	TcpListenStop  *ebpf.Program `ebpf:"tcp_listen_stop"`
	Udp4Bind       *ebpf.Program `ebpf:"udp4_bind"`
	Udp6Bind       *ebpf.Program `ebpf:"udp6_bind"`
	UdpUnbind      *ebpf.Program `ebpf:"udp_unbind"`
}

func (p *trackerPrograms) Close() error {
	return _TrackerClose(
		p.TcpListenStart,
		p.TcpListenStop,
		p.Udp4Bind,
		p.Udp6Bind,
		p.UdpUnbind,
	)
}

func _TrackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracker_bpfel.o
var _TrackerBytes []byte
